### ISSUE TITLE
Add Tree-Sitter as a submodule

### ISSUE THREAD

**Issue by ThomasWitte** [sp-uulm/MiniLua#16]
Downloading the tree-sitter dependencies as part of the build is really intransparent. Network access during the build might also cause problems if not connected to the internet and makes deterministic/reproducible builds impossible.

**Comment by Lythenas** [comment]
I'm guessing by "submodule" you mean a git submodule. They are harder to use and maintain. And you run into annoying issues if you don't know that you have to look for them.

We could just run the "git submodule" commands to download and update them in cmake but that would basically be the same we do now with `FetchContent`.

`FetchContent` downloads the dependencies during configuration of cmake (when you execute `cd build; cmake ..` or the `./scripts/setup_build.sh`) not during the build itself. So you don't need internet to build.

We can specify the commit instead of just the tag in FetchContent to make it *more reproducible*. But to make the build actually reproducible we would need to do a lot more extra work (e.g. specifying the **exact** version of compiler, cmake and all other tools).

**Comment by ThomasWitte** [comment]
I am a fan of simple(r) build processes, cmake is complicated enough. Cloning the repository and initializing the submodules is not hard, maintaining a build process that runs all kind of magic scripts is (IMO). I think, requiring internet access during the build is just a terrible idea in general.

If I want to change the version of tree-sitter I am building against, I can A) use standard git commands to set the version using submodules or B) must know the build scripts to find the location of the commit/tag that needs to be changed.

Trying to automate the initialization of git submodules in CMake sounds even more terrifying. CMake is just a build tool, please don't make a cargo/npm/gradle replacement out of it.

**Comment by Lythenas** [comment]
Adding more steps to the build process does not make it *simpler* but whatever.

Tasks that need to be done:

- move dependencies to git submodules
- figure out a way to include them in cmake
- automate git submodules with a script
- document the build process
